POST http://localhost:8000/products/ HTTP/1.1
content-type: application/json

{
    "name": "Produto 4",
    "price": 10,
    "description": "Produto 4 descrição"
}

###

GET http://localhost:8000/products/:_id HTTP/1.1
content-type: application/json

###

GET http://localhost:8000/products HTTP/1.1
content-type: application/json

###